<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Version>1.1.2</Version>
    <AssemblyVersion>1.1.2.0</AssemblyVersion>
    <FileVersion>1.1.2.0</FileVersion>
    <AssemblyTitle>NetPulse</AssemblyTitle>
    <Product>NetPulse</Product>
    <Authors>NetPulse</Authors>
    <Company>NetPulse</Company>
    <Description>NetPulse Network Diagnostic &amp; Optimization Tool</Description>
    <Copyright>Copyright © 2026 NetPulse</Copyright>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\app.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Sentry" Version="6.11.0" />
    <PackageReference Include="System.Management" Version="10.0.12" />
  </ItemGroup>

</Project>
